
included: # paths to include during linting. `--path` is ignored if present.
  - ${PROJECT_NAME}
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - ${PROJECT_NAME}/Pods
line_length:
  - 170
